/**
 * O'zbekcha → ruscha lug'at.
 *
 * Kalit — interfeysdagi o'zbekcha matnning aynan o'zi. Tarjima JSX
 * darajasida qo'llanadi (src/lib/i18n-runtime/jsx-runtime.ts), shuning
 * uchun bu yerga qator qo'shilsa, u butun platformada o'zi ishlaydi.
 *
 * Atamalar ataylab 1C dagidek olingan: menejerlar yillar davomida
 * «Заказ покупателя», «Номенклатура», «Контрагент» bilan ishlagan.
 *
 * Lug'atda yo'q matn o'zbekcha ko'rinadi — ya'ni to'ldirilmagan joy
 * hech narsani sindirmaydi.
 */

export const RU: Record<string, string> = {
  /* ---------------------------------------------- Umumiy tugmalar */
  'Bekor': 'Отмена',
  'Bekor qilish': 'Отменить',
  'Saqlash': 'Сохранить',
  'Yopish': 'Закрыть',
  'Ochish': 'Открыть',
  "O'chirish": 'Удалить',
  'Tahrirlash': 'Редактировать',
  'Yaratish': 'Создать',
  "Qo'shish": 'Добавить',
  'Yangilash': 'Обновить',
  'Tanlash': 'Выбрать',
  'Tozalash': 'Очистить',
  'Yuborish': 'Отправить',
  'Yuklash': 'Загрузить',
  'Orqaga': 'Назад',
  'Chiqish': 'Выход',
  'Hisoblash': 'Рассчитать',
  "Qayta hisoblash": 'Пересчитать',
  'Chop etish': 'Печать',
  "O'tkazish": 'Провести',
  "O'tkazish va yopish": 'Провести и закрыть',
  'Yozish': 'Записать',
  'Kiritish': 'Ввести',
  "Ko'chirish": 'Переместить',
  'Nusxa': 'Копия',
  'Nusxasini yaratish': 'Создать копию',
  'Asosida yaratish': 'Создать на основании',
  'Asosida yaratish — Sotuv': 'Создать на основании — Реализация',
  'Saralash': 'Сортировка',
  'Qidiruv': 'Поиск',
  'Qidiruv…': 'Поиск…',
  'Tanlang…': 'Выберите…',
  'Hammasi': 'Все',
  'Batafsil': 'Подробнее',
  'Hammasini yopish': 'Закрыть все',
  'Rad etish': 'Отклонить',
  'Tasdiqlash': 'Утверждение',
  'Bajarildi': 'Выполнено',
  'Natija': 'Результат',
  'Tema': 'Тема',
  'Menyu': 'Меню',
  'Insert': 'Insert',
  'Ctrl+Enter': 'Ctrl+Enter',
  'Ctrl+S': 'Ctrl+S',

  /* ---------------------------------------------- Umumiy ustunlar */
  'Sana': 'Дата',
  'Sanasi': 'Дата',
  'Summa': 'Сумма',
  'Summa:': 'Сумма:',
  'Holat': 'Статус',
  'Izoh': 'Комментарий',
  'Turi': 'Вид',
  'Nomi': 'Наименование',
  'Ism': 'Имя',
  'Raqam': 'Номер',
  'Raqami': 'Номер',
  'Kod': 'Код',
  'Faol': 'Активен',
  'faol emas': 'не активен',
  'Amal': 'Действия',
  'Tartib': 'Порядок',
  'Telefon': 'Телефон',
  'Telefoni': 'Телефон',
  'Email': 'Email',
  'Manzil': 'Адрес',
  'Manzil:': 'Адрес:',
  'Miqdor': 'Количество',
  'Narx': 'Цена',
  'Jami': 'Итого',
  'Jami:': 'Итого:',
  'Qoldiq': 'Остаток',
  'Qoldiq:': 'Остаток:',
  'Qolgan': 'Осталось',
  'Sabab': 'Причина',
  'Sabab:': 'Причина:',
  'Muddat': 'Срок',
  'Vaqt': 'Время',
  'Bugun': 'Сегодня',
  'Oldinroq': 'Ранее',
  'Kun': 'День',
  'Oy': 'Месяц',
  'Birlik': 'Ед. изм.',
  'Valyuta': 'Валюта',
  'Kurs': 'Курс',
  "so'm": 'сум',
  "So'mda": 'В сумах',
  'Guruh': 'Группа',
  'Toifa': 'Категория',
  'Kategoriya': 'Категория',
  'Qator': 'Строка',
  'Qatorlar': 'Строки',
  "Qator qo'shish": 'Добавить строку',
  'Yuqoriga': 'Вверх',
  'Pastga': 'Вниз',
  'Dan': 'С',
  'Gacha': 'По',
  'Sanadan': 'С даты',
  'Qiymat': 'Значение',
  "Ko'rsatkich": 'Показатель',
  'Ixtiyoriy': 'Необязательно',
  'Standart': 'По умолчанию',
  'Doimiy': 'Постоянный',
  "O'zgaruvchi": 'Переменный',
  'Boshqa': 'Прочее',
  'Yangi': 'Новый',
  'Asosiy': 'Основное',
  "Qo'shimcha": 'Дополнительно',
  'Tarix': 'История',
  'Hisobotlar': 'Отчёты',
  'Tafsilot': 'Детали',
  'Qisqacha': 'Кратко',
  'Topilmadi': 'Не найдено',
  'Hujjat topilmadi': 'Документ не найден',
  "Ma'lumot": 'Данные',
  "Ma'lumot yo'q": 'Нет данных',
  'Yozuvlar': 'Записи',
  "Yozuv yo'q": 'Записей нет',
  'Soliq': 'Налог',

  /* ---------------------------------------------- Navigatsiya */
  'Kunlik panel': 'Рабочий стол',
  'AI tahlil': 'AI-анализ',
  'Vazifalar': 'Задачи',
  'Sotuv': 'Продажи',
  'Mijozlar': 'Клиенты',
  'Voronka': 'Воронка',
  'Uchrashuvlar': 'Встречи',
  'Debitor': 'Дебиторка',
  'Ombor': 'Склад',
  'Xaridlar': 'Закупки',
  'Tovar va narx': 'Номенклатура и цены',
  'Moliya va P&L': 'Финансы и P&L',
  'Xodimlar': 'Сотрудники',
  'Arxiv': 'Архив',
  'Sozlamalar': 'Настройки',
  'Kompaniyalar': 'Компании',
  'Moliya': 'Финансы',
  'Bosh sahifa': 'Главная',

  /* ---------------------------------------------- Kontragentlar */
  'Mijoz': 'Клиент',
  'Xaridor': 'Покупатель',
  'Postavshik': 'Поставщик',
  'Postavshiklar': 'Поставщики',
  'Menejer': 'Менеджер',
  'Sotuv menejeri': 'Менеджер по продажам',
  'Buxgalter': 'Бухгалтер',
  "ta'sischi": 'учредитель',
  'Xodim': 'Сотрудник',
  'Lavozim': 'Должность',
  'Rol': 'Роль',
  'STIR': 'ИНН',
  'Aloqa': 'Контакты',
  'Aloqa shaxsi': 'Контактное лицо',
  'Oxirgi aloqa': 'Последний контакт',
  "Qo'ng'iroq": 'Звонок',
  'Yangi mijoz': 'Новый клиент',
  'Mijoz nomi…': 'Наименование клиента…',
  'Mijoz topilmadi': 'Клиент не найден',
  'Hamma menejer': 'Все менеджеры',
  'Taqsimlash': 'Распределить',
  'Taqsimlanmagan': 'Не распределён',
  'Jami sotuv': 'Всего продаж',
  "O'rtacha marja": 'Средняя маржа',
  'Kredit limiti': 'Кредитный лимит',
  'Oxirgi sotuv': 'Последняя продажа',
  "Postavshik nomi…": 'Наименование поставщика…',
  'Ism yoki tashkilot': 'Имя или организация',

  /* ---------------------------------------------- Hujjatlar */
  'Hujjat': 'Документ',
  'Hujjatlar': 'Документы',
  "Hujjat yo'q": 'Документов нет',
  'Xaridor buyurtmasi': 'Заказ покупателя',
  'Mijozga sotuv': 'Реализация товаров',
  'Tovar kelishi': 'Поступление товаров',
  'Xaridordan qaytarish': 'Возврат товаров от покупателя',
  'Omborlar orasida ko‘chirish': 'Перемещение товаров',
  'Qaytarish': 'Возврат',
  'Xarid': 'Закупка',
  'Xarid (postlangan)': 'Закупка (проведена)',
  'Yangi xarid': 'Новая закупка',
  'Yangi sotuv': 'Новая продажа',
  'Yangi tovar': 'Новая номенклатура',
  'Buyurtma': 'Заказ',
  "Buyurtma yo'q": 'Заказов нет',
  'Qoralama': 'Черновик',
  'Postlangan': 'Проведён',
  'Postlanmagan': 'Не проведён',
  'Bekor qilingan': 'Отменён',
  'bekor qilingan': 'отменён',
  'Shartnoma': 'Договор',
  'Shartnomalar': 'Договоры',
  'Asosiy shartnoma': 'Основной договор',
  'Shartnoma turi': 'Вид договора',
  'Hisob-faktura': 'Счёт-фактура',
  'Hisob-fakturalar': 'Счета-фактуры',
  'Yuk xati': 'Товарная накладная',
  'Yuk xatlari': 'Товарные накладные',
  'Tijorat taklifi': 'Коммерческое предложение',
  "Amal qilish muddati": 'Срок действия',
  'Tovarlar': 'Товары',
  "Tovar kiritilmagan": 'Товары не указаны',
  "Hujjatga o'tkazish": 'Перенести в документ',
  "Hujjat hali saqlanmagan": 'Документ ещё не сохранён',
  'Excel uchun CSV': 'CSV для Excel',

  /* ---------------------------------------------- Ombor */
  'Tovar': 'Номенклатура',
  "Tovar yo'q": 'Нет товара',
  "Qoldiq yo'q": 'Нет остатка',
  'Nomenklatura': 'Номенклатура',
  "Nomenklatura bo'sh": 'Номенклатура пуста',
  "O'lchov birligi": 'Единица измерения',
  "O'lchov birliklari": 'Единицы измерения',
  'Omborlar': 'Склады',
  'Hamma ombor': 'Все склады',
  'Ombor:': 'Склад:',
  'Ombor qiymati': 'Стоимость склада',
  'Tovar kategoriyalari': 'Категории номенклатуры',
  'Hamma kategoriya': 'Все категории',
  'Barcha turkumlar': 'Все группы',
  'Partiya': 'Партия',
  'Partiyalar': 'Партии',
  "Partiya yo'q": 'Партий нет',
  'Harakatlar': 'Движения',
  "Harakat yo'q": 'Движений нет',
  'Inventarizatsiya': 'Инвентаризация',
  'Inventarizatsiya ochish': 'Открыть инвентаризацию',
  'Inventarizatsiyani o‘tkazish': 'Провести инвентаризацию',
  'Sanalgan': 'Подсчитано',
  'Sanalmagan': 'Не подсчитано',
  'Tizim bo‘yicha': 'По системе',
  'Haqiqiy': 'Фактически',
  'Farq': 'Отклонение',
  'Farq topilgan': 'Найдены отклонения',
  'Jami tovar': 'Всего товаров',
  'Zaxira': 'Запас',
  'Kunlik sarf': 'Расход в день',
  'Yetadi': 'Хватит на',
  'Kelgan': 'Поступило',
  'Kirgan': 'Приход',
  'Kirim': 'Приход',
  'Chiqim': 'Расход',
  'Sotildi': 'Продано',
  'Jami sotilgan': 'Всего продано',
  'Buyurtma kerak': 'Нужен заказ',
  'Muzlagan tovar': 'Неликвиды',
  'Tranzit (yo‘lda)': 'В пути',
  'Band qilindi': 'Зарезервировано',
  'band qilingan': 'зарезервировано',
  'Chiqarilgan': 'Отгружено',
  'Yuk chiqmagan': 'Не отгружено',
  'Yuk': 'Отгрузка',
  'Yuk rejimi': 'Режим отгрузки',
  'Yukni chiqarish': 'Отгрузить',
  'Chiqarish': 'Отгрузка',
  'Chiqariladi': 'К отгрузке',
  'Chiqarish sanasi': 'Дата отгрузки',
  'Qayerdan': 'Откуда',
  'Qayerga': 'Куда',
  'Tovarni tanlang…': 'Выберите номенклатуру…',
  'Tovar nomi yoki kodi…': 'Наименование или код…',
  'Nomi, kodi yoki shtrix-kodi…': 'Наименование, код или штрихкод…',
  'Tovar tanlash': 'Подбор номенклатуры',
  'Tanlangan tovarlar': 'Выбранные товары',
  "Ro'yxatdan tanlash": 'Подбор из списка',
  "Ko'chirish hujjati yo'q": 'Нет документов перемещения',
  'Omborda hisobga olinadi': 'Учитывается на складе',

  /* ---------------------------------------------- Narx va marja */
  'Narx turi': 'Тип цен',
  'Narxni yangilash': 'Обновить цену',
  'Narx shu toifadan olinadi': 'Цена берётся из этого типа',
  'Tan narx': 'Себестоимость',
  'Tovar tan narxi': 'Себестоимость товаров',
  'haqiqiy tan narx': 'фактическая себестоимость',
  'Marja': 'Маржа',
  'Marja:': 'Маржа:',
  'Min. marja': 'Мин. маржа',
  'Ustama': 'Наценка',
  'Chegirma': 'Скидка',
  'Maks. chegirma': 'Макс. скидка',
  'QQS': 'НДС',
  'QQS siz': 'без НДС',
  'Summa ichidagi QQS': 'НДС в сумме',
  'Foyda': 'Прибыль',
  'Yalpi foyda': 'Валовая прибыль',
  'Yalpi foyda:': 'Валовая прибыль:',
  'Yalpi marja': 'Валовая маржа',
  'Sof foyda': 'Чистая прибыль',
  'Sof summa': 'Сумма без возвратов',
  "Yo'qotilgan foyda": 'Упущенная прибыль',
  'Asos': 'Основание',

  /* ---------------------------------------------- Pul */
  'Kassa': 'Касса',
  'Naqd kassa': 'Наличная касса',
  'Bank hisobi': 'Банковский счёт',
  'Kassa jurnali': 'Журнал кассы',
  'Jami kassa': 'Итого по кассе',
  'Kassa holati': 'Состояние кассы',
  "Kassalar bo'yicha taqsimot": 'Распределение по кассам',
  'Kassa va bank hisoblari': 'Кассы и банковские счета',
  'Kassalar orasida ko‘chirish': 'Перемещение между кассами',
  'Qaysi kassadan': 'Из какой кассы',
  'Qayerga tushdi': 'Куда поступило',
  "To'lov": 'Оплата',
  "To'lov —": 'Оплата —',
  "To'lov turi": 'Вид оплаты',
  "To'lov muddati": 'Срок оплаты',
  "To'lov muddatlari": 'Сроки оплаты',
  "To'lov kiritildi": 'Оплата проведена',
  "To'langan": 'Оплачено',
  "to'langan": 'оплачено',
  "To'langan:": 'Оплачено:',
  "To'lanmagan": 'Не оплачено',
  "to'lanmagan": 'не оплачено',
  "To'lash": 'Оплатить',
  "To'landi": 'Оплачено',
  "To'lanadi": 'К выплате',
  'Naqd': 'Наличные',
  "Bank o'tkazmasi": 'Банковский перевод',
  'Karta': 'Карта',
  'Avans': 'Аванс',
  'Avansi': 'Аванс',
  'Avansimiz': 'Наш аванс',
  'Qarz': 'Долг',
  'Qarz:': 'Долг:',
  'Qarzi': 'Долг',
  'Qarzlar': 'Кредиты и займы',
  'Qarzimiz': 'Наш долг',
  'Sof qarz': 'Чистый долг',
  'Qarz qoldig‘i': 'Остаток долга',
  "Qarz to'lovi —": 'Погашение долга —',
  'Faol qarz': 'Активные займы',
  "Faol qarz yo'q": 'Активных займов нет',
  'Oylik to‘lov': 'Ежемесячный платёж',
  'Muddati o‘tgan': 'Просрочено',
  'Muddati o‘tgan qarz': 'Просроченная задолженность',
  'Kechikish': 'Просрочка',
  'Kechikkan kunlar': 'Дней просрочки',
  'Bizga qarzdor': 'Нам должны',
  'Bizga qarz:': 'Нам должны:',
  'Biz qarzdormiz': 'Мы должны',
  'Biz qarzdormiz:': 'Мы должны:',
  'biz qarzdormiz': 'мы должны',
  'qarzdormiz.': 'мы должны.',
  "Biz to'lashimiz kerak": 'Мы должны оплатить',
  'Mijozlar qarzi': 'Дебиторская задолженность',
  'Mijozlarim qarzi': 'Долги моих клиентов',
  'Postavshiklarga qarz': 'Долг поставщикам',
  'Postavshiklarga avans': 'Авансы поставщикам',
  'Mijozlardan olingan avans': 'Авансы от клиентов',
  'Kredit va investor qarzi': 'Кредиты и займы инвесторов',
  'Boshlang‘ich qarz': 'Начальный долг',
  'Boshlang‘ich qoldiq': 'Начальный остаток',
  'Undirish': 'Собираемость',
  'faqat undirilgan': 'только собранное',
  'Mijozda qolgan': 'Осталось у клиента',
  'Naqd oqim': 'Движение денег',
  'Sof oqim': 'Чистый поток',
  'Pozitsiya': 'Позиция',
  'Sof pozitsiya': 'Чистая позиция',
  'Sof': 'Чисто',
  'Aktiv': 'Активы',
  'Jami aktiv': 'Итого активы',
  'Majburiyat': 'Обязательства',
  'Jami majburiyat': 'Итого обязательства',
  'Naqd va bank': 'Наличные и банк',
  'Ombordagi tovar': 'Товар на складе',
  'Kontragent / izoh': 'Контрагент / комментарий',
  'Kontragent, toifa, hujjat…': 'Контрагент, статья, документ…',
  'Kimdan / kimga': 'От кого / кому',
  'Kimda': 'У кого',
  'Kimga': 'Кому',
  'Kim olgan': 'Кто получил',
  'Yo‘nalish': 'Направление',

  /* ---------------------------------------------- Moliya, byudjet */
  'Foyda va zarar': 'Прибыли и убытки',
  'Reja': 'План',
  'Rejadagi': 'По плану',
  'Fakt': 'Факт',
  'Reja va byudjet': 'План и бюджет',
  'Sotuv rejasi': 'План продаж',
  'Sotuv (fakt)': 'Продажи (факт)',
  'Sotuv (reja)': 'Продажи (план)',
  'Sotuv (QQSsiz)': 'Продажи (без НДС)',
  'Bajarilishi': 'Выполнение',
  'Oylik reja bajarilishi': 'Выполнение плана за месяц',
  'Oylik rejam': 'Мой план на месяц',
  'Modda': 'Статья',
  'Harajat': 'Расход',
  'Harajatlar': 'Расходы',
  'Harajat moddasi': 'Статья расходов',
  'Harajat moddalari': 'Статьи расходов',
  'Harajat kiritish': 'Ввести расход',
  'Harajat kiritilmagan': 'Расходы не введены',
  'Birinchi harajat': 'Первый расход',
  'Jami doimiy harajat': 'Итого постоянные расходы',
  'O‘zgaruvchi harajat': 'Переменные расходы',
  'Doimiy harajat': 'Постоянные расходы',
  'Foyda solig‘i': 'Налог на прибыль',
  'OPERATSION FOYDA': 'ОПЕРАЦИОННАЯ ПРИБЫЛЬ',
  'SOF FOYDA': 'ЧИСТАЯ ПРИБЫЛЬ',
  'YALPI FOYDA': 'ВАЛОВАЯ ПРИБЫЛЬ',
  'Operatsion sof': 'Операционный поток',
  'Moliyaviy sof': 'Финансовый поток',
  'Davr bo‘yicha jami': 'Итого за период',
  'Davr yo‘q': 'Период не задан',
  'Byudjet qatorlari yo‘q': 'Нет строк бюджета',
  'Oylik summa': 'Сумма в месяц',
  'Formula': 'Формула',
  'Oylik fondi': 'Фонд оплаты труда',
  'Oklad va soliqni qayta hisoblash': 'Пересчитать оклады и налоги',

  /* ---------------------------------------------- Xodimlar */
  'Hisob ochish': 'Создать учётную запись',
  'Hisob ochildi': 'Учётная запись создана',
  'Yangi xodim hisobi': 'Новая учётная запись',
  'Jamoa': 'Команда',
  'Jami xodim': 'Всего сотрудников',
  'Faol xodim': 'Активных сотрудников',
  'Xodim topilmadi': 'Сотрудник не найден',
  'Xodim kartochkasi': 'Карточка сотрудника',
  'Xodim o‘chirilsinmi?': 'Удалить сотрудника?',
  'Oklad': 'Оклад',
  'Oylik oklad': 'Месячный оклад',
  'Joriy oklad': 'Текущий оклад',
  'Bonus': 'Бонус',
  'Bonus %': 'Бонус %',
  'Bonus bazasi': 'База бонуса',
  'Bonussiz': 'Без бонуса',
  'Oylik': 'Зарплата',
  'Oylikdan soliq': 'Налог с зарплаты',
  'Oylik hisob-kitobi': 'Расчёт зарплаты',
  'Oylik hisoblanmagan': 'Зарплата не рассчитана',
  'Oylik tarixi': 'История зарплат',
  'Hisoblanmagan': 'Не начислено',
  'Qo‘lga tegadi': 'На руки',
  'Qo‘lga': 'На руки',
  'Rag‘bat': 'Премия',
  "Rag'bat (qo'shiladi)": 'Премия (добавляется)',
  'Jazo': 'Штраф',
  "Jazo (ushlab qolinadi)": 'Штраф (удерживается)',
  'Jazo / rag‘bat': 'Штраф / премия',
  'Jazo va rag‘bat': 'Штрафы и премии',
  'Oyiga ushlash': 'Удержание в месяц',
  'Oylikdan bo‘lib ushlab qolinadi': 'Удерживается из зарплаты частями',
  'Avans va qarz': 'Авансы и долги',
  'Avans qoldig‘i': 'Остаток аванса',
  'Avans berilmagan': 'Авансы не выдавались',
  'Yopilmagan avans': 'Непогашенный аванс',
  'Davomat': 'Табель',
  'Davomat va ta‘til': 'Табель и отпуска',
  'Bugungi davomatim': 'Мой табель на сегодня',
  'Keldi': 'Пришёл',
  'Keldim': 'Пришёл',
  'Ketdi': 'Ушёл',
  'Ketdim': 'Ушёл',
  'Ishladi': 'Отработано',
  'Ishlagan soat': 'Отработано часов',
  'Ta‘til': 'Отпуск',
  'Ta‘til va ruxsat': 'Отпуска и отгулы',
  'Ta‘til / ruxsat so‘rovi': 'Заявка на отпуск / отгул',
  'Yillik ta‘til normasi': 'Норма отпуска за год',
  'Ishlatilgan': 'Использовано',
  'So‘rov': 'Заявка',
  "So'rov yo'q": 'Заявок нет',
  'KPI va reyting': 'KPI и рейтинг',
  'Ishga olish sanasi': 'Дата приёма',
  'Ishga kirgan': 'Принят',
  'Bo‘shatish': 'Увольнение',
  'Bo‘shatildi': 'Уволен',
  'Bo‘shatilgan': 'Уволен',
  'Bo‘shatish sanasi': 'Дата увольнения',
  'Bo‘shatish sababi': 'Причина увольнения',
  'Qayta ishga olish': 'Принять повторно',
  'Ish topshirish': 'Передача дел',
  'Topshirildi': 'Передано',
  'Rasmiylashtirish': 'Оформление',
  'Yakuniy hisob-kitob': 'Окончательный расчёт',
  'Mehnat': 'Трудовые данные',
  'Mehnat tarixi': 'Трудовая история',
  'Shaxsiy': 'Личные данные',
  'Sinov muddati': 'Испытательный срок',
  'Shartnoma tugaydi': 'Договор заканчивается',
  'Buyruq raqami': 'Номер приказа',
  'Buyruq sanasi': 'Дата приказа',
  'Tug‘ilgan sana': 'Дата рождения',
  'Pasport': 'Паспорт',
  'Seriya va raqam': 'Серия и номер',
  'JSHSHIR': 'ПИНФЛ',
  'Favqulodda aloqa': 'Экстренный контакт',
  'Favqulodda holatda kim': 'Кому звонить в экстренном случае',
  'Parol': 'Пароль',
  'Yangi parol': 'Новый пароль',
  'Parolni almashtirish': 'Сменить пароль',
  'Yangi parol yaratish': 'Создать новый пароль',
  'Vaqtinchalik parol': 'Временный пароль',
  'To‘liq ism': 'Полное имя',
  'To‘liq ismingiz': 'Ваше полное имя',
  'Ism Familiya': 'Имя Фамилия',
  'Kamida 6 belgi': 'Минимум 6 символов',
  'Oxirgi 60 kun': 'Последние 60 дней',
  'Bu yil olgani': 'Взято в этом году',
  'Bu kunda yozuv yo‘q': 'За этот день записей нет',

  /* ---------------------------------------------- CRM */
  'Imkoniyat': 'Сделка',
  'Imkoniyat yo‘q': 'Сделок нет',
  'Bosqich': 'Этап',
  'Ehtimol': 'Вероятно',
  'Ehtimollik': 'Вероятность',
  'Ehtimollik bilan': 'С учётом вероятности',
  'Kutilgan': 'Ожидается',
  'Kutilgan sana': 'Ожидаемая дата',
  'Taxminiy summa': 'Предварительная сумма',
  'Voronkada': 'В воронке',
  'Yutilgan': 'Выиграно',
  'Yutish darajasi': 'Конверсия',
  'Yo‘qotildi': 'Проиграно',
  'Nega yo‘qotildi': 'Почему проиграно',
  'Yo‘qotish sabablari': 'Причины проигрыша',
  'Sotuv voronkasi bosqichlari': 'Этапы воронки продаж',
  'Uchrashuv': 'Встреча',
  'Uchrashuv yo‘q': 'Встреч нет',
  'Uchrashuv bo‘lmadi': 'Встреча не состоялась',
  'Uchrashuv natijasi': 'Итог встречи',
  'Nima kelishildi': 'О чём договорились',
  'Mavzu': 'Тема',
  'Joy': 'Место',
  'Tashkilotchi': 'Организатор',
  'Bog‘lanmagan': 'Не связано',
  'Oldinda': 'Предстоит',
  'Natija yozilmagan': 'Итог не записан',
  'Aloqa tarixi': 'История контактов',
  'Aloqa yozuvi': 'Запись о контакте',
  'Aloqa yozilmagan': 'Контакты не записаны',
  'Sotuv tarixi': 'История продаж',
  'Sotuv yo‘q': 'Продаж нет',
  'Birinchi sotuv': 'Первая продажа',
  'Sotuv kiritish': 'Ввести продажу',
  'Sotuvni ochish': 'Открыть продажу',
  'Keyingi aloqa sanasi': 'Дата следующего контакта',
  'Qo‘ng‘iroq —': 'Звонок —',
  'Qo‘ng‘iroq navbati bo‘sh': 'Очередь звонков пуста',
  'Bugun qo‘ng‘iroq': 'Звонки на сегодня',
  'Bugun qo‘ng‘iroq qilinadi': 'Позвонить сегодня',
  'Va‘da qilingan summa': 'Обещанная сумма',
  'Javob bermadi': 'Не ответил',
  'Hujjat/faktura kerak': 'Нужен документ/счёт',
  'To‘lashga va‘da berdi': 'Обещал оплатить',
  'Hozir puli yo‘q': 'Сейчас нет денег',
  'Summa bilan rozi emas': 'Не согласен с суммой',
  'Qisman to‘lay olaman dedi': 'Готов оплатить частично',
  'Hamma sabab': 'Все причины',
  'Eng ko‘p olgan tovarlari': 'Самые частые товары',
  'Eng ko‘p sotilgan': 'Самые продаваемые',
  'Eng yaxshi marja': 'Лучшая маржа',
  'Eng yaxshi mijoz': 'Лучший клиент',
  'Eng yaxshi menejer': 'Лучший менеджер',
  'Hali sotuv yo‘q': 'Продаж пока нет',
  'Bu oy sotuv': 'Продажи за месяц',
  'Bu oy sotuvim': 'Мои продажи за месяц',
  'Bugungi uchrashuv': 'Встречи сегодня',

  /* ---------------------------------------------- Vazifalar */
  'Vazifa': 'Задача',
  'Muhimlik': 'Приоритет',
  'Shoshilinch': 'Срочно',
  'Oddiy': 'Обычный',
  'Past': 'Низкий',
  'Yakunlangan': 'Завершено',
  'Ishlanmoqda': 'В работе',
  'Ishlanmagan': 'Не обработано',
  'Menda': 'На мне',
  'Jami ochiq': 'Всего открытых',
  'Nima': 'Что',
  'Nima qilish kerak': 'Что нужно сделать',
  'Tayinlanmagan': 'Не назначено',

  /* ---------------------------------------------- Tasdiqlash */
  'Tasdiq kutmoqda': 'Ждёт утверждения',
  'Tasdiq kutilmoqda.': 'Ждёт утверждения.',
  'Kutayotgan': 'В ожидании',
  'Kutmoqda': 'В ожидании',
  'Hal qilingan': 'Решено',
  'So‘ragan': 'Запросил',
  'Tasdiqlandi': 'Утверждено',
  'Rad etildi': 'Отклонено',
  'Rad etildi.': 'Отклонено.',
  'Rad etilgan': 'Отклонено',
  'darhol o‘tkaziladi': 'проводится сразу',

  /* ---------------------------------------------- Sozlamalar */
  'Umumiy': 'Общие',
  'Sotuv va narx': 'Продажи и цены',
  'AI': 'AI',
  'Ofis': 'Офис',
  'Shaxsda': 'В лице',
  'Spravochniklar': 'Справочники',
  'Rollar va ruxsatlar': 'Роли и права',
  'Yangi rol': 'Новая роль',
  'Rol nomi': 'Название роли',
  'Rol tanlanmagan': 'Роль не выбрана',
  'Asosiy rol': 'Базовая роль',
  'tizim roli': 'системная роль',
  'Ma‘lumot qamrovi': 'Область данных',
  'Bu rol nima qila oladi': 'Что может эта роль',
  'Hamma mijoz va sotuv': 'Все клиенты и продажи',
  'Faqat o‘ziga biriktirilgan mijozlar': 'Только свои клиенты',
  'Shu rolning nusxasini yaratish': 'Создать копию этой роли',
  'Mijoz toifalari (narx darajalari)': 'Категории клиентов (типы цен)',
  'Kasr xona': 'Знаков после запятой',
  'Rang': 'Цвет',
  'BUYURTMA': 'ЗАКАЗ',
  'CHEGIRMA': 'СКИДКА',
  'BUYURTMA (kun)': 'ЗАКАЗ (дней)',
  'CHEGIRMA (kun)': 'СКИДКА (дней)',

  /* ---------------------------------------------- Telegram, AI */
  'Telegram': 'Telegram',
  'Telegramni ulash': 'Подключить Telegram',
  'Ulash kodini olish': 'Получить код подключения',
  'Ulanish kodi': 'Код подключения',
  'Ulangan': 'Подключён',
  'Uzish': 'Отключить',
  'Botda nima bor': 'Что умеет бот',
  '15 daqiqa': '15 минут',
  'amal qiladi.': 'действует.',
  'Savol bering': 'Задайте вопрос',
  'Savolingizni yozing…': 'Напишите свой вопрос…',
  'Brifing yangilash': 'Обновить сводку',
  'Brifing hali tayyorlanmagan': 'Сводка ещё не готова',
  'AI tavsiyalari': 'Рекомендации AI',
  'Signal': 'Сигнал',
  'Signallar': 'Сигналы',
  'Taklif qilinadigan tovar': 'Рекомендуемый товар',

  /* ---------------------------------------------- Bildirishnomalar */
  'Bildirishnomalar': 'Уведомления',
  'Yangi bildirishnoma yo‘q': 'Новых уведомлений нет',
  "Hammasini o'qildi deb belgilash": 'Отметить все как прочитанные',

  /* ---------------------------------------------- Kurs */
  'USD': 'USD',
  'Olish kursi': 'Курс покупки',
  'Sotish kursi': 'Курс продажи',
  "Olish/sotish kursini o'zgartirish": 'Изменить курс покупки/продажи',
  'Kurs eskirgan': 'Курс устарел',
  'Hozir yangilash': 'Обновить сейчас',

  /* ---------------------------------------------- Yetkazish */
  'Yetkazish': 'Доставка',
  'Yetkazib berish': 'Доставка',
  'Yetkazish manzili': 'Адрес доставки',
  'Yetkazilgan sana': 'Дата доставки',
  'Yetkazilgan:': 'Доставлено:',
  'Haydovchi': 'Водитель',
  'Haydovchi:': 'Водитель:',
  'Mashina': 'Машина',
  'Mashina raqami': 'Номер машины',
  'Reys': 'Рейс',

  /* ---------------------------------------------- Arxiv */
  'Arxiv bo‘sh': 'Архив пуст',
  'O‘chirgan': 'Кто удалил',
  'Qachon': 'Когда',
  'Barcha turlar': 'Все виды',
  'Nega o‘chiryapsiz': 'Почему удаляете',
  'Masalan: xato kiritilgan': 'Например: введено по ошибке',
  'Masalan: ishdan bo‘shadi': 'Например: уволился',
  "O'chirilgan hujjatlar shu yerda to'liq saqlanadi":
    'Удалённые документы хранятся здесь целиком',
  "Hujjat o'chirilsa, u shu yerga tushadi":
    'Удалённый документ попадает сюда',
  'Nom, raqam yoki sabab': 'Название, номер или причина',

  /* ---------------------------------------------- Kompaniya, kirish */
  'Kompaniya': 'Компания',
  'Kompaniya nomi': 'Название компании',
  'Kompaniya yo‘q': 'Компаний нет',
  'Kompaniya biriktirilmagan': 'Компания не привязана',
  'Kompaniya to‘xtatilgan': 'Компания приостановлена',
  'Yangi kompaniya ro‘yxatdan o‘tkazish': 'Регистрация новой компании',
  'Kompaniya ro‘yxatdan o‘tkazish': 'Зарегистрировать компанию',
  'Tizimga kirish': 'Вход в систему',
  'Birinchi kirish': 'Первый вход',
  'Hisob faol emas': 'Учётная запись не активна',
  'Ariza': 'Заявка',
  'Ariza kutmoqda': 'Заявка на рассмотрении',
  'Ariza ko‘rib chiqilmoqda': 'Заявка рассматривается',
  'Ariza rad etildi': 'Заявка отклонена',
  'To‘xtatish': 'Приостановить',
  'To‘xtatilgan': 'Приостановлено',
  'Yoqish': 'Включить',
  'Hisobim bor': 'У меня есть аккаунт',
  'Ichida nima bor': 'Что внутри',
  'Qanday boshlanadi': 'Как начать',
  'sotuvdan foydagacha': 'от продажи до прибыли',
  'Ruxsat yo‘q': 'Нет доступа',

  /* ---------------------------------------------- Uzunroq matnlar */
  'Bu bo‘limni ko‘rish uchun ruxsat kerak.':
    'Для просмотра этого раздела нужны права.',
  'Bu bo‘lim faqat platforma egasiga ko‘rinadi.':
    'Этот раздел виден только владельцу платформы.',
  'Qidiruv yoki filtrni o‘zgartiring.':
    'Измените поиск или фильтр.',
  'Qidiruv yoki kategoriya filtrini o‘zgartiring.':
    'Измените поиск или фильтр по категории.',
  'Sana oralig‘ini yoki filtrni o‘zgartiring.':
    'Измените период или фильтр.',
  'Sana oralig‘ini o‘zgartiring yoki yangi kirim/chiqim kiriting.':
    'Измените период или введите новый приход/расход.',
  'Marja yoki limitdan oshgan hujjatlar':
    'Документы с маржой ниже порога или суммой выше лимита',
  'Marja eng past chegaradan pastga tushsa yoki summa limitdan oshsa, hujjat shu yerga tushadi.':
    'Если маржа опускается ниже порога или сумма превышает лимит, документ попадает сюда.',
  'Bir kundan ortiq kutayotgan': 'Ждут больше суток',
  'Sotuv tasdiqlanmaguncha omborga tegmaydi':
    'Пока продажа не утверждена, склад не затрагивается',
  'AI bazani o‘qib topgan narsalar. Qarorni siz qabul qilasiz.':
    'AI прочитал базу и нашёл это. Решение принимаете вы.',
  'Muddati o‘tgan yoki 3 kun ichida to‘lanishi kerak':
    'Просрочено или к оплате в ближайшие 3 дня',
  'Muddati o‘tgan qarz yo‘q — yaxshi holat.':
    'Просроченной задолженности нет — хорошо.',
  'Muddati o‘tgan yoki 3 kun ichida to‘lanishi kerak bo‘lgan qarz yo‘q.':
    'Нет долгов, просроченных или подлежащих оплате в ближайшие 3 дня.',
  'Qarz ham, avans ham yo‘q': 'Нет ни долга, ни аванса',
  'Zaxira sozlamada belgilangan kundan kam qolgan':
    'Запаса меньше, чем задано в настройках',
  'Zaxira belgilangan normadan yuqori.': 'Запас выше заданной нормы.',
  'Zaxira sozlamadagi normadan kam': 'Запас ниже нормы из настроек',
  'Har biri o‘z foiziga ko‘paytirilgan':
    'Каждая умножена на свою вероятность',
  'Sof pozitsiya (aktiv − majburiyat)': 'Чистая позиция (активы − обязательства)',
  'Pozitsiya, foyda-zarar, naqd oqim, byudjet va qarzlar':
    'Позиция, прибыли и убытки, движение денег, бюджет и займы',
  'Bizda bor yoki bizga qarzdor': 'Что у нас есть или нам должны',
  'Eng katta qarzdan boshlab': 'Начиная с самого большого долга',
  'eng eski hujjatdan boshlab': 'начиная с самого старого документа',
  'Barcha raqamlar so‘mda, QQSsiz': 'Все суммы в сумах, без НДС',
  'Reja va byudjet bo‘limidan oy qo‘shing.':
    'Добавьте месяц в разделе «План и бюджет».',
  'Foyda ≠ pul. Bu yerda kassada haqiqatda nima bo‘lgani ko‘rinadi.':
    'Прибыль ≠ деньги. Здесь видно, что на самом деле происходило в кассе.',
  'To‘lov va harajat kiritilgach shu yerda ko‘rinadi.':
    'Появится здесь после ввода оплат и расходов.',
  'Sotuv rejasi — oy bo‘yicha. O‘zgartirsangiz P&L darhol qayta hisoblanadi.':
    'План продаж — помесячно. При изменении P&L пересчитывается сразу.',
  'Oklad va soliq qatorlari xodimlar ro‘yxatidan hisoblanadi.':
    'Строки оклада и налогов считаются по списку сотрудников.',
  'Kim haqiqatan foyda keltirayotgani — aylanma emas, marja va undirish muhim':
    'Кто действительно приносит прибыль — важен не оборот, а маржа и собираемость',
  'Aylanma emas, keltirgan foyda bo‘yicha': 'Не по обороту, а по прибыли',
  'Foyda va undirish bo‘yicha': 'По прибыли и собираемости',
  'Yalpi foyda bo‘yicha': 'По валовой прибыли',
  'Bu oyda sotuv yo‘q': 'В этом месяце продаж нет',
  'Xodim endi tizimga kira oladi.': 'Теперь сотрудник может войти в систему.',
  'Faqat shu yerda bir marta ko‘rsatiladi.':
    'Показывается только здесь и только один раз.',
  'faqat shu yerda bir marta': 'только здесь и только один раз',
  'Ta‘til, kasallik yoki shaxsiy ruxsat so‘rovini shu yerdan yuborasiz.':
    'Отсюда отправляется заявка на отпуск, больничный или отгул.',
  'Ishga olish, oklad va lavozim o‘zgarishlari shu yerda to‘planadi.':
    'Здесь собираются приём на работу, изменения оклада и должности.',
  'Shu oyning oylik hisobiga avtomatik kiradi.':
    'Автоматически войдёт в расчёт зарплаты этого месяца.',
  'Oylik hisobiga avtomatik kiradi': 'Автоматически входит в расчёт зарплаты',
  'Bo‘shatishda topshirilishi kerak': 'Должно быть сдано при увольнении',
  'Mijoz bilan uchrashuvni shu yerga yozasiz — keyin natijasi ham shu yerda qoladi.':
    'Здесь записывается встреча с клиентом — и её итог остаётся тут же.',
  'Qo‘ng‘iroq va uchrashuvlarni yozib borsangiz, tarix shu yerda to‘planadi.':
    'Если записывать звонки и встречи, история будет собираться здесь.',
  'Mijoz qiziqish bildirdi, lekin hali sotuv bo‘lmadi — shuni shu yerga yozasiz.':
    'Клиент проявил интерес, но продажи ещё не было — это записывается здесь.',
  'Mijoz so‘ragan, lekin hali rasmiylashtirilmagan tovarni shu yerga yozasiz.':
    'Здесь записывается товар, который клиент запросил, но заказ ещё не оформлен.',
  'Postavshiklardan tovar qabul qilish — partiya va tan narx shu yerdan yaraladi':
    'Приём товара от поставщиков — отсюда создаются партии и себестоимость',
  'Postavshikdan tovar kelganda shu yerga kiritasiz. Postlanganda partiya yaraladi va FIFO tan narx ishlay boshlaydi.':
    'Сюда вводится приход товара от поставщика. При проведении создаётся партия и начинает работать себестоимость по FIFO.',
  'Xarid hujjati postlangach partiya yaratiladi va qoldiq paydo bo‘ladi.':
    'После проведения закупки создаётся партия и появляется остаток.',
  'Xarid hujjati postlanganda partiya avtomatik yaratiladi.':
    'При проведении закупки партия создаётся автоматически.',
  'Xarid, sotuv va ko‘chirish hujjatlari shu yerga tushadi.':
    'Сюда попадают закупки, продажи и перемещения.',
  'Pul berilgan, tovar kelmagan': 'Деньги выданы, товар не поступил',
  'Pul berdik, tovar kelmagan': 'Деньги отдали, товар не пришёл',
  'Avval nomenklatura va xarid kiriting — signallar sotuv tarixidan hisoblanadi.':
    'Сначала введите номенклатуру и закупку — сигналы считаются по истории продаж.',
  'Hamma parametr shu yerda. Kodda hech qanday raqam qotirilmagan — o‘zgartirsangiz butun tizim darhol qayta hisoblaydi.':
    'Все параметры здесь. В коде ни одно число не зашито — при изменении вся система сразу пересчитывается.',
  'Topshiriqni shu yerdan berasiz — kimga, qachongacha va nima uchun.':
    'Отсюда ставится задача — кому, до какого срока и зачем.',
  'Sotuv kiritilgach shu yerda eng yaxshi tovar, mijoz, marja va menejer ko‘rinadi':
    'После ввода продаж здесь видны лучшие товары, клиенты, маржа и менеджеры',
  'Birinchi sotuv hujjati kiritilgandan keyin reytinglar va kross-sotuv tavsiyalari avtomatik hisoblanadi.':
    'После первого документа продажи рейтинги и рекомендации по кросс-продажам считаются автоматически.',
  'Shu kategoriyadan xarid qiladigan boshqa mijozlar olgan, lekin bu mijoz hali olmagan tovarlar':
    'Товары, которые берут другие клиенты этой категории, а этот клиент ещё не брал',
  '60 kundan beri xarid qilmagan': 'Не покупает более 60 дней',
  'Tarix hujjat birinchi marta yozilgandan keyin to‘plana boshlaydi.':
    'История начинает собираться после первой записи документа.',
  'Bu hujjatga hali o‘zgarish kiritilmagan.':
    'В этот документ изменения пока не вносились.',
  'Tarix bo‘sh': 'История пуста',
  'Haqiqiy qoldiqni sanab, tizimdagisi bilan solishtirish uchun hujjat oching.':
    'Откройте документ, чтобы пересчитать фактический остаток и сверить с системой.',
  'Inventarizatsiya o‘tkazilmagan': 'Инвентаризация не проводилась',
  'Masalan: oylik inventarizatsiya, komissiya a‘zolari…':
    'Например: ежемесячная инвентаризация, члены комиссии…',
  'Ochish (yoki qatorni ikki marta bosing)':
    'Открыть (или двойной щелчок по строке)',
  'Tasdiqlash — tovar band qilinadi': 'Утвердить — товар резервируется',
  'Faqat o‘tkazilgan va yuki chiqqan sotuvlardan qaytarish mumkin.':
    'Возврат возможен только по проведённым и отгруженным продажам.',
  'Bu sotuvdagi hamma tovar allaqachon qaytarilgan yoki hali chiqmagan.':
    'Весь товар по этой продаже уже возвращён или ещё не отгружен.',
  'Tovar qaytarilsa sotuv kartochkasidagi «Qaytarish» tugmasi orqali rasmiylashtiriladi.':
    'Возврат оформляется кнопкой «Возврат» в карточке продажи.',
  'Faqat chiqarilgan tovarni qaytarish mumkin.':
    'Вернуть можно только отгруженный товар.',
  'Qaytariladigan tovar yo‘q': 'Нет товара к возврату',
  'Qaytariladi': 'К возврату',
  'Qaytarilgan': 'Возвращено',
  'Qaytarilgan:': 'Возвращено:',
  'Qaytarish summasi': 'Сумма возврата',
  'Qaytarish yo‘q': 'Возвратов нет',
  'Mos sotuv topilmadi': 'Подходящая продажа не найдена',
  'Boshqa sotuvni tanlash': 'Выбрать другую продажу',
  'Mijozga yuborish uchun — PDF sifatida saqlanadi':
    'Для отправки клиенту — сохраняется как PDF',
  'Ro‘yxatdan bir nechta tovarni tanlash':
    'Подбор нескольких товаров из списка',
  'Mijoz yoki hujjat raqami…': 'Клиент или номер документа…',
  'Mijoz yoki hujjat…': 'Клиент или документ…',
  'Xaridor tanlanmagan': 'Покупатель не выбран',
  'Avval xaridorni tanlang.': 'Сначала выберите покупателя.',
  'Hujjat kartochkasi — to‘lov, yuk, qaytarish':
    'Карточка документа — оплата, отгрузка, возврат',
  'Oddiy savol yozsangiz AI javob beradi':
    'Напишите обычный вопрос — AI ответит',
  'Muhim bildirishnomalar o‘zi kelib turadi':
    'Важные уведомления приходят сами',
  'Bildirishnomalar va savol-javob shu yerga keladi':
    'Уведомления и ответы приходят сюда',
  'Saqlanmagan o‘zgarishlar': 'Несохранённые изменения',
  'Hamma holat': 'Все статусы',
  'Hamma tovar yetarli': 'Товара достаточно',
  'Buyurtma berish kerak': 'Нужно заказать',
  'Jami ochiq': 'Всего открыто',
  'hamma pul harakati': 'все движения денег',
  'Oxirgi sotuvlar': 'Последние продажи',
  'Birinchi tovarni qo‘shish': 'Добавить первый товар',
  'Birinchi xarid': 'Первая закупка',
  'Xarid hujjati yo‘q': 'Документов закупки нет',
  'Postavshik qarzi': 'Долг поставщику',
  'Kiritilsa vazifa yaratiladi': 'При вводе создаётся задача',
  'suratga olinadi': 'фиксируется',
  'Kim ochdi': 'Кто открыл',
  'Qator yo‘q': 'Строк нет',

  /* ---------------------------------------------- Ochiq sahifa */
  'Savdo va distributsiya uchun': 'Для торговли и дистрибуции',
  'Biznesingiz bitta ekranda:': 'Ваш бизнес на одном экране:',
  'Kirish': 'Вход',
  'Boshlash': 'Начать',
  'Kompaniyani ro‘yxatdan o‘tkazish': 'Зарегистрировать компанию',
  'Ro‘yxatdan o‘tish': 'Регистрация',
  'O‘zbek tilida': 'На узбекском языке',
  'QQS bilan ishlaydi': 'Работает с НДС',
  'Ma‘lumot ko‘chirib beriladi': 'Перенесём ваши данные',
  'Bugun boshlang': 'Начните сегодня',
  'Boshqaruv platformasi · O‘zbekiston': 'Платформа управления · Узбекистан',
  'Sotuv, ombor, moliya va xodimlar': 'Продажи, склад, финансы и сотрудники',

  'Sales Growth — sotuv, ombor, moliya va xodimlarni bir joyda boshqaradigan platforma. Har bir hujjat, har bir so‘m va har bir dona tovar izma-iz kuzatiladi.':
    'Sales Growth — платформа, где продажи, склад, финансы и сотрудники в одном месте. Каждый документ, каждый сум и каждая единица товара на виду.',

  '1C ga o‘xshash hujjatlar': 'Документы как в 1С',
  'Menejerlaringiz yillar davomida 1C da ishlagan bo‘lsa, qayta o‘rganishi shart emas. Buyruqlar paneli, zakladkalar, Insert va Ctrl+Enter — hammasi o‘sha joyda.':
    'Если ваши менеджеры годами работали в 1С, переучиваться не придётся. Командная панель, закладки, Insert и Ctrl+Enter — всё на своих местах.',

  'Ombor va partiya hisobi': 'Складской и партионный учёт',
  'FIFO bo‘yicha tan narx. Qaysi partiyadan qancha ketgani, erkin qoldiq qancha qolgani va nima tugab qolayotgani doim ko‘rinib turadi.':
    'Себестоимость по FIFO. Всегда видно, сколько ушло из какой партии, каков свободный остаток и что заканчивается.',

  'Pul zanjiri uzilmaydi': 'Денежная цепочка не рвётся',
  'Sotuvdan qarzga, qarzdan to‘lovga, to‘lovdan kassaga — har bir so‘m izma-iz kuzatiladi. Pul qayerdadir qotib qolmaydi.':
    'От продажи к долгу, от долга к оплате, от оплаты к кассе — каждый сум прослеживается. Деньги нигде не зависают.',

  'Haqiqiy marja': 'Настоящая маржа',
  'Foyda QQS siz sof summadan hisoblanadi. Marja chegaradan pastga tushsa hujjat tasdiqqa tushadi — sizdan so‘ramay sotib bo‘lmaydi.':
    'Прибыль считается от суммы без НДС. Если маржа опускается ниже порога, документ уходит на утверждение — без вас продать не получится.',

  'Kim nimani ko‘radi': 'Кто что видит',
  'Rollarni o‘zingiz sozlaysiz: menejer faqat o‘z mijozini ko‘radi, tan narx va kassa yopiq. Cheklov interfeysda emas, bazada turadi.':
    'Роли настраиваете сами: менеджер видит только своих клиентов, себестоимость и касса закрыты. Ограничение не в интерфейсе, а в базе.',

  'Kassa, qarzdorlar va tugayotgan tovar botga keladi. Tasdiqlashni ham to‘g‘ridan-to‘g‘ri Telegramdan qilasiz.':
    'Касса, должники и заканчивающийся товар приходят в бот. Утверждать тоже можно прямо из Telegram.',

  'Bo‘limlar bir-biriga ulangan: ombordagi harakat moliyada, sotuvdagi marja esa menejer ko‘rsatkichida darhol aks etadi.':
    'Разделы связаны между собой: движение по складу сразу отражается в финансах, а маржа продажи — в показателях менеджера.',

  'Ariza yuborasiz': 'Отправляете заявку',
  'Kompaniya nomi va aloqa ma’lumotlari — bir daqiqalik ish.':
    'Название компании и контакты — работа на минуту.',
  'Tasdiqlaymiz': 'Мы подтверждаем',
  'Odatda bir ish kuni ichida. Tasdiqlangach xabar keladi.':
    'Обычно в течение рабочего дня. После подтверждения придёт уведомление.',
  'Ishlay boshlaysiz': 'Начинаете работать',
  'Ombor, birliklar, narx turlari va rollar tayyor holda beriladi.':
    'Склад, единицы измерения, типы цен и роли уже настроены.',
  'Ariza bir daqiqa oladi. Tasdiqlangach kompaniyangiz ishga tayyor holda beriladi.':
    'Заявка займёт минуту. После подтверждения компания будет готова к работе.',

  /* ---------------------------------------------- Kirish ekrani */
  'ism@kompaniya.uz': 'ism@kompaniya.uz',
  'Ta‘sischi sifatida boshlash': 'Начать как учредитель',
  'Masalan: Zuhriddin Ismoilov': 'Например: Зухриддин Исмоилов',
  'Masalan: Oq Yo‘l Savdo MChJ': 'Например: ООО «Oq Yo‘l Savdo»',
  'Bu email tizimga kirdi, lekin birorta kompaniyaga bog‘lanmagan.':
    'Этот email вошёл в систему, но не привязан ни к одной компании.',
  'Kompaniyangiz ta‘sischisiga murojaat qiling — u Xodimlar bo‘limida hisobingizni biriktirib qo‘yadi.':
    'Обратитесь к учредителю вашей компании — он привяжет вашу учётную запись в разделе «Сотрудники».',
  'Odatda bir ish kuni ichida hal qilinadi. Tasdiqlangach shu yerga qaytib kiring — boshqa hech narsa qilish shart emas.':
    'Обычно решается в течение рабочего дня. После подтверждения просто зайдите сюда снова — больше ничего делать не нужно.',
  'Tizimda hali xodim yo‘q. O‘zingizni ta‘sischi qilib ro‘yxatdan o‘tkazasiz.':
    'В системе ещё нет сотрудников. Зарегистрируйте себя как учредителя.',
  'Sabab ko‘rsatilmagan. Platforma egasi bilan bog‘laning.':
    'Причина не указана. Свяжитесь с владельцем платформы.',

  /* ---------------------------------------------- Modullar ro'yxati */
  'Sotuv va buyurtma': 'Продажи и заказы',
  'Mijozlar va CRM': 'Клиенты и CRM',
  'Moliya va P&L ': 'Финансы и P&L ',
  'Xodimlar va oylik': 'Сотрудники и зарплата',
  'AI tahlil ': 'AI-анализ ',
  'Hujjat chop etish': 'Печать документов',
}
